### PR TITLE
Organize exceptions thrown

### LINKED ISSUE #81: Reduce number of exceptions thrown
Instead, we should favor nullable return types or `sealed class`es.

http://www.douevencode.com/articles/2018-09/kotlin-error-handling/ summarizes it well.

Exceptions currently (`develop` branch) being thrown:

**`core`**
- `RemoteException`
- `ConnectionLostException`
- `OutOfOrderGattCallbackException`
- `GattErrorStatusException`

**`keep-alive`**
- `NotReadyException`

**`throw`**
- `GattStatusException`
- `RemoteException`
- `ConnectionLostException`

### PR DESCRIPTION
**Pull request by twyatt**
`IOException` chosen for failures where an I/O operation did not succeed. It is expected that library users will catch these exceptions and decide if operation should be retried or if more extreme measures should be taken (e.g. reconnect prior to retrying).

Closes #81.

### `core`

| Class                             | Base Exception          |
|-----------------------------------|-------------------------|
| `RemoteException`                 | `Exception`                 |
| `ConnectionLostException`         | `IOException`           |
| `GattStatusException`             | `IOException`           |
| `OutOfOrderGattCallbackException` | `IllegalStateException` |

- `OutOfOrderGattCallbackException` should never occur. This failure is not recoverable and the behavior of future requests is undefined. Library user should allow app to crash or re-establish connect (to reset callback state). If this exception is ever encountered it should be reported so it may be investigated.
- `RemoteException` occurs when the Android system fails to execute a request, it is unlikely that retrying the operation will succeed until the user intervenes (e.g. turns on BLE).

### `keep-alive`

| Class               | Base Exception |
|---------------------|----------------|
| `NotReadyException` | `IOException`  |

### `throw`

| Class                          | Base Exception |
|--------------------------------|----------------|
| `GattStatusException` (`core`) | `IOException`  |
| `RemoteException`              | `Exception`  |
| `ConnectionLostException`      | `IOException`  |

## 📓  Notes

Since `SharedFlow` is not yet officially released, this branch was developed against [internally built Coroutines artifacts](https://github.com/JuulLabs/kotlinx.coroutines-sharedflow); this PR will be merged into `internal` branch (see #86 for details).

### CODE REVIEW

File: core/src/main/java/gatt/GattConnection.kt [hunk 1]
```diff
@@ -45,9 +45,12 @@ interface GattConnection {
...
 
-class GattErrorStatusException internal constructor(
-    val event: OnConnectionStateChange
-) : IOException("Received $event")
+class GattStatusException(message: String?) : IOException(message) {
+    constructor(
+        status: GattStatus,
+        prefix: String
+    ) : this("$prefix failed with status ${status.asGattStatusString()}")
+}
```
Comment (cedrickcooke) [inline core/src/main/java/gatt/GattConnection.kt:53]: Should these constructors be `internal` like the other exceptions?

Comment (twyatt) [reply core/src/main/java/gatt/GattConnection.kt:53]: Yes, but...
This exception is also thrown from `throw` module.

I've tried utilizing `friend-paths` (to give `throw` module access to `internal` definitions in `core`) but could not get it working. 😢 

Spent about 3 hours trying to get the friend paths working before giving up and just accepting this little bit of cruft on the public API.

**Review by cedrickcooke — APPROVED** [review]

File: core/src/main/java/gatt/GattConnection.kt (hunk 1 above)
Comment (cedrickcooke) [reply core/src/main/java/gatt/GattConnection.kt:53]: I really wish Kotlin had _way_ more visibility modifiers. Something like Android's `@RestrictTo` but at a language level.

**Comment by sdonn3** [comment]
lgtm!

**Review by sdonn3 — APPROVED** [review]

**Comment by twyatt** [comment]
Small update: This PR was brought into `develop` via a fast-forwarding of `develop` to `internal` (that was dropped). So some slight modifications of the squashed commit may exist in the final commit that landed in `develop`.
